import type { Product, Category, Brand, Profile, Order, OrderItem } from "@/types";

// ========================
// MOCK USER (demo mode)
// ========================
export const mockUser: Profile = {
  id: "mock-user-1",
  full_name: "Usuario Demo",
  phone: "+54 11 1234-5678",
  address: {
    street: "Av. Corrientes 1234",
    city: "Buenos Aires",
    state: "CABA",
    postal_code: "1043",
    country: "Argentina",
  },
  role: "customer",
  created_at: "2025-06-01T00:00:00Z",
  updated_at: "2026-01-15T00:00:00Z",
};

// ========================
// MOCK ORDERS (demo mode)
// ========================
export const mockOrders: Order[] = [
  {
    id: "aabb1122-0001-0001-0001-000000000001",
    user_id: "mock-user-1",
    status: "delivered",
    total: 113000,
    shipping_address: {
      street: "Av. Corrientes 1234",
      city: "Buenos Aires",
      state: "CABA",
      postal_code: "1043",
      country: "Argentina",
    },
    created_at: "2026-01-15T10:30:00Z",
    updated_at: "2026-01-20T14:00:00Z",
  },
  {
    id: "aabb1122-0002-0002-0002-000000000002",
    user_id: "mock-user-1",
    status: "shipped",
    total: 85000,
    shipping_address: {
      street: "Av. Corrientes 1234",
      city: "Buenos Aires",
      state: "CABA",
      postal_code: "1043",
      country: "Argentina",
    },
    created_at: "2026-02-28T08:00:00Z",
    updated_at: "2026-03-01T12:00:00Z",
  },
  {
    id: "aabb1122-0003-0003-0003-000000000003",
    user_id: "mock-user-1",
    status: "confirmed",
    total: 450000,
    shipping_address: {
      street: "Av. Corrientes 1234",
      city: "Buenos Aires",
      state: "CABA",
      postal_code: "1043",
      country: "Argentina",
    },
    created_at: "2026-03-10T15:00:00Z",
    updated_at: "2026-03-10T16:30:00Z",
  },
  {
    id: "aabb1122-0004-0004-0004-000000000004",
    user_id: "mock-user-1",
    status: "pending",
    total: 28000,
    shipping_address: {
      street: "Av. Corrientes 1234",
      city: "Buenos Aires",
      state: "CABA",
      postal_code: "1043",
      country: "Argentina",
    },
    created_at: "2026-03-11T20:00:00Z",
    updated_at: "2026-03-11T20:00:00Z",
  },
];

// Order items per order_id
export const mockOrderItems: Record<string, OrderItem[]> = {
  "aabb1122-0001-0001-0001-000000000001": [
    {
      id: "item-1-1",
      order_id: "aabb1122-0001-0001-0001-000000000001",
      product_id: "1",
      quantity: 1,
      unit_price: 85000,
      created_at: "2026-01-15T10:30:00Z",
    },
    {
      id: "item-1-2",
      order_id: "aabb1122-0001-0001-0001-000000000001",
      product_id: "13",
      quantity: 8,
      unit_price: 3500,
      created_at: "2026-01-15T10:30:00Z",
    },
  ],
  "aabb1122-0002-0002-0002-000000000002": [
    {
      id: "item-2-1",
      order_id: "aabb1122-0002-0002-0002-000000000002",
      product_id: "1",
      quantity: 1,
      unit_price: 85000,
      created_at: "2026-02-28T08:00:00Z",
    },
  ],
  "aabb1122-0003-0003-0003-000000000003": [
    {
      id: "item-3-1",
      order_id: "aabb1122-0003-0003-0003-000000000003",
      product_id: "3",
      quantity: 1,
      unit_price: 450000,
      created_at: "2026-03-10T15:00:00Z",
    },
  ],
  "aabb1122-0004-0004-0004-000000000004": [
    {
      id: "item-4-1",
      order_id: "aabb1122-0004-0004-0004-000000000004",
      product_id: "5",
      quantity: 1,
      unit_price: 28000,
      created_at: "2026-03-11T20:00:00Z",
    },
  ],
};

export const mockBrands: Brand[] = [
  { id: "1", name: "Hikvision", logo: null, description: "Líder mundial en videovigilancia", created_at: "" },
  { id: "2", name: "Dahua", logo: null, description: "Innovación en seguridad electrónica", created_at: "" },
  { id: "3", name: "Axis", logo: null, description: "Pioneros en cámaras IP de red", created_at: "" },
  { id: "4", name: "Reolink", logo: null, description: "Seguridad inteligente para todos", created_at: "" },
  { id: "5", name: "Ezviz", logo: null, description: "Smart home security", created_at: "" },
  { id: "6", name: "TP-Link Tapo", logo: null, description: "Vigilancia conectada", created_at: "" },
];

export const mockCategories: Category[] = [
  { id: "1", name: "Cámaras IP", slug: "camaras-ip", description: "Cámaras de red de alta definición", image: null, created_at: "" },
  { id: "2", name: "Domo", slug: "domo", description: "Cámaras tipo domo discretas", image: null, created_at: "" },
  { id: "3", name: "PTZ", slug: "ptz", description: "Cámaras con movimiento Pan-Tilt-Zoom", image: null, created_at: "" },
  { id: "4", name: "Exterior", slug: "exterior", description: "Resistentes a la intemperie", image: null, created_at: "" },
  { id: "5", name: "Interior", slug: "interior", description: "Para uso en interiores", image: null, created_at: "" },
  { id: "6", name: "NVR/DVR", slug: "nvr-dvr", description: "Grabadores de video en red", image: null, created_at: "" },
  { id: "7", name: "Accesorios", slug: "accesorios", description: "Soportes, cables y más", image: null, created_at: "" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Hikvision DS-2CD2143G2-I 4MP AcuSense",
    slug: "hikvision-ds-2cd2143g2-i-4mp",
    description: "Cámara IP domo 4MP con inteligencia artificial AcuSense, visión nocturna infrarroja de 40m, resistente al vandalismo IK10.",
    price: 85000,
    stock: 15,
    brand_id: "1",
    category_id: "2",
    images: [],
    specs: { resolution: "4MP (2688×1520)", night_vision: "40m IR", ip_rating: "IP67/IK10", connectivity: "PoE/RJ45", fov: "103°", compression: "H.265+", audio: "Built-in mic" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[1],
  },
  {
    id: "2",
    name: "Dahua IPC-HDW2849H-S-IL 8MP Smart Dual Light",
    slug: "dahua-ipc-hdw2849h-s-il-8mp",
    description: "Cámara IP domo 8MP con luz dual inteligente, detección de personas y vehículos, visión nocturna a color.",
    price: 120000,
    stock: 8,
    brand_id: "2",
    category_id: "2",
    images: [],
    specs: { resolution: "8MP (3840×2160) 4K", night_vision: "30m color / 30m IR", ip_rating: "IP67/IK10", connectivity: "PoE", fov: "102°", compression: "H.265+" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[1],
    category: mockCategories[1],
  },
  {
    id: "3",
    name: "Hikvision DS-2DE4425IWG-E PTZ 4MP 25x",
    slug: "hikvision-ds-2de4425iwg-e-ptz-4mp",
    description: "Cámara PTZ de red 4MP con zoom óptico 25x, seguimiento automático de objetivos, resistente a la intemperie.",
    price: 450000,
    stock: 3,
    brand_id: "1",
    category_id: "3",
    images: [],
    specs: { resolution: "4MP", zoom: "25x óptico / 16x digital", night_vision: "100m IR", ip_rating: "IP66", connectivity: "PoE+/Ethernet", fov: "58.1° ~ 2.5°" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[2],
  },
  {
    id: "4",
    name: "Reolink RLC-810A 4K PoE Exterior",
    slug: "reolink-rlc-810a-4k-poe",
    description: "Cámara exterior 4K con detección inteligente de personas, vehículos y mascotas. Resistente IP66.",
    price: 65000,
    stock: 22,
    brand_id: "4",
    category_id: "4",
    images: [],
    specs: { resolution: "8MP (3840×2160) 4K", night_vision: "30m IR", ip_rating: "IP66", connectivity: "PoE", fov: "89°", storage: "MicroSD hasta 256GB" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[3],
    category: mockCategories[3],
  },
  {
    id: "5",
    name: "Ezviz C6N 1080p Interior WiFi",
    slug: "ezviz-c6n-1080p-interior",
    description: "Cámara interior WiFi con rotación 360°, seguimiento de movimiento, audio bidireccional.",
    price: 28000,
    stock: 45,
    brand_id: "5",
    category_id: "5",
    images: [],
    specs: { resolution: "1080p Full HD", night_vision: "10m IR", connectivity: "WiFi 2.4GHz", fov: "360° horizontal", storage: "MicroSD hasta 256GB / Cloud", audio: "Bidireccional" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[4],
    category: mockCategories[4],
  },
  {
    id: "6",
    name: "TP-Link Tapo C320WS Exterior Color Night Vision",
    slug: "tp-link-tapo-c320ws-exterior",
    description: "Cámara exterior 4MP con visión nocturna a color, resistente al agua y polvo.",
    price: 38000,
    stock: 30,
    brand_id: "6",
    category_id: "4",
    images: [],
    specs: { resolution: "4MP (2560×1440)", night_vision: "30m color", ip_rating: "IP66", connectivity: "WiFi 2.4/5GHz", fov: "89°", storage: "MicroSD hasta 512GB" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[5],
    category: mockCategories[3],
  },
  {
    id: "7",
    name: "Dahua NVR4108HS-8P-EI NVR 8 Canales PoE",
    slug: "dahua-nvr4108hs-8p-ei-8-canales",
    description: "Grabador de red 8 canales con 8 puertos PoE integrados, soporte H.265+, resolución hasta 4K.",
    price: 180000,
    stock: 6,
    brand_id: "2",
    category_id: "6",
    images: [],
    specs: { channels: 8, resolution: "Hasta 4K", compression: "H.265+/H.264", storage: "Hasta 2 HDDs 20TB", connectivity: "8x PoE + 1x RJ45", poe: "8 puertos 802.3af/at" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[1],
    category: mockCategories[5],
  },
  {
    id: "8",
    name: "Hikvision DS-7608NI-K2 NVR 8 Canales",
    slug: "hikvision-ds-7608ni-k2-nvr-8",
    description: "NVR 8 canales de alta definición, soporte H.265+, decodificación hasta 4K, 2 bahías HDD.",
    price: 155000,
    stock: 10,
    brand_id: "1",
    category_id: "6",
    images: [],
    specs: { channels: 8, resolution: "Hasta 8MP", compression: "H.265+", storage: "2x HDD hasta 10TB c/u", connectivity: "1x RJ45", frame_rate: "80Mbps entrada" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[5],
  },
  {
    id: "9",
    name: "Axis P3245-V 2MP Fixed Dome",
    slug: "axis-p3245-v-2mp-fixed-dome",
    description: "Cámara domo fija de gama profesional con enfoque automático, WDR Forensic Capture, resistente IK10.",
    price: 210000,
    stock: 4,
    brand_id: "3",
    category_id: "2",
    images: [],
    specs: { resolution: "2MP (1080p)", night_vision: "IR incorporado", ip_rating: "IP42/IK10", connectivity: "PoE IEEE 802.3af", compression: "H.264/H.265/MJPEG", audio: "Sí" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[2],
    category: mockCategories[1],
  },
  {
    id: "10",
    name: "Reolink Argus 3 Pro Solar 4MP",
    slug: "reolink-argus-3-pro-solar",
    description: "Cámara inalámbrica 4MP con panel solar incluido, batería recargable, sin necesidad de cables.",
    price: 75000,
    stock: 18,
    brand_id: "4",
    category_id: "4",
    images: [],
    specs: { resolution: "4MP (2560×1440)", night_vision: "10m color / 10m IR", ip_rating: "IP65", connectivity: "WiFi 2.4GHz", storage: "MicroSD + Nube", power: "Solar + batería 5200mAh" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[3],
    category: mockCategories[3],
  },
  {
    id: "11",
    name: "Hikvision DS-2CD2T47G2-L 4MP ColorVu",
    slug: "hikvision-ds-2cd2t47g2-l-4mp-colorvu",
    description: "Cámara bala exterior 4MP con tecnología ColorVu para imagen a color las 24hs, con audio integrado.",
    price: 95000,
    stock: 12,
    brand_id: "1",
    category_id: "4",
    images: [],
    specs: { resolution: "4MP (2688×1520)", night_vision: "60m color 24/7", ip_rating: "IP67", connectivity: "PoE", fov: "86°", audio: "Built-in mic", compression: "H.265+" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[3],
  },
  {
    id: "12",
    name: "Dahua IPC-HFW2849S-S-IL 8MP Full-Color",
    slug: "dahua-ipc-hfw2849s-s-il-8mp",
    description: "Cámara bala exterior 8MP con visión nocturna a color completa, luz blanca y LED IR.",
    price: 110000,
    stock: 9,
    brand_id: "2",
    category_id: "4",
    images: [],
    specs: { resolution: "8MP 4K (3840×2160)", night_vision: "30m color", ip_rating: "IP67", connectivity: "PoE", fov: "102°", compression: "H.265+" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[1],
    category: mockCategories[3],
  },
  {
    id: "13",
    name: "Soporte de Pared Universal para Cámaras Domo",
    slug: "soporte-pared-universal-domo",
    description: "Soporte de pared de aluminio resistente compatible con la mayoría de cámaras domo. Permite ajuste de ángulo.",
    price: 3500,
    stock: 100,
    brand_id: null,
    category_id: "7",
    images: [],
    specs: { dimensions: "120×80×60mm", weight: "250g", lens: "Aluminio anodizado" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: undefined,
    category: mockCategories[6],
  },
  {
    id: "14",
    name: "Cable UTP Cat6 305m Exterior",
    slug: "cable-utp-cat6-305m-exterior",
    description: "Rollo de cable UTP categoría 6 de 305 metros para uso exterior con doble cubierta.",
    price: 42000,
    stock: 20,
    brand_id: null,
    category_id: "7",
    images: [],
    specs: { dimensions: "305m por rollo", connectivity: "Cat6 UTP", ip_rating: "Para exterior" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: undefined,
    category: mockCategories[6],
  },
  {
    id: "15",
    name: "Ezviz DB2C Video Timbre WiFi 1080p",
    slug: "ezviz-db2c-video-timbre",
    description: "Video timbre inteligente con cámara 1080p, detección de movimiento y comunicación bidireccional.",
    price: 52000,
    stock: 25,
    brand_id: "5",
    category_id: "5",
    images: [],
    specs: { resolution: "1080p Full HD", fov: "155° ultra wide", connectivity: "WiFi 2.4GHz", audio: "Bidireccional", ip_rating: "IP65", storage: "MicroSD / Nube" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[4],
    category: mockCategories[4],
  },
  {
    id: "16",
    name: "Hikvision DS-2CD2386G2-ISU/SL 8MP AcuSense",
    slug: "hikvision-ds-2cd2386g2-isu-sl-8mp",
    description: "Cámara domo 8MP 4K AcuSense con sirena y luz estroboscópica integrada para disuasión activa.",
    price: 145000,
    stock: 7,
    brand_id: "1",
    category_id: "2",
    images: [],
    specs: { resolution: "8MP 4K (3840×2160)", night_vision: "30m color / 30m IR", ip_rating: "IP67/IK10", connectivity: "PoE", audio: "Sirena integrada + altavoz", compression: "H.265+" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[1],
  },
  {
    id: "17",
    name: "Dahua SD49425XB-HNR PTZ 4MP 25x AI",
    slug: "dahua-sd49425xb-hnr-ptz-4mp-ai",
    description: "Cámara PTZ 4MP con IA avanzada, zoom óptico 25x, seguimiento automático y reconocimiento facial.",
    price: 520000,
    stock: 2,
    brand_id: "2",
    category_id: "3",
    images: [],
    specs: { resolution: "4MP (2688×1520)", zoom: "25x óptico", night_vision: "100m IR", ip_rating: "IP66/IK10", connectivity: "PoE+", fov: "Varifocal 5.4-135mm" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[1],
    category: mockCategories[2],
  },
  {
    id: "18",
    name: "TP-Link Tapo C210 3MP Interior Pan/Tilt",
    slug: "tp-link-tapo-c210-3mp-interior",
    description: "Cámara interior WiFi 3MP con rotación horizontal 360° y vertical 114°, seguimiento automático de movimiento.",
    price: 22000,
    stock: 60,
    brand_id: "6",
    category_id: "5",
    images: [],
    specs: { resolution: "3MP (2304×1296)", night_vision: "9m IR", connectivity: "WiFi 2.4GHz", fov: "360° × 114°", storage: "MicroSD hasta 512GB / Nube", audio: "Bidireccional" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[5],
    category: mockCategories[4],
  },
  {
    id: "19",
    name: "Hikvision DS-7616NI-K2/16P NVR 16 Canales PoE",
    slug: "hikvision-ds-7616ni-k2-16p-nvr",
    description: "NVR 16 canales con 16 puertos PoE, resolución hasta 4K, soporte hasta 8MP por canal.",
    price: 380000,
    stock: 4,
    brand_id: "1",
    category_id: "6",
    images: [],
    specs: { channels: 16, resolution: "Hasta 4K/8MP", compression: "H.265+", storage: "2x HDD hasta 10TB c/u", poe: "16 puertos 802.3af/at", frame_rate: "160Mbps" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[0],
    category: mockCategories[5],
  },
  {
    id: "20",
    name: "Reolink RLC-823A 4K PoE con Spotlight",
    slug: "reolink-rlc-823a-4k-spotlight",
    description: "Cámara exterior 4K PoE con focos LED de color y sirena, visión nocturna a color activa.",
    price: 82000,
    stock: 14,
    brand_id: "4",
    category_id: "4",
    images: [],
    specs: { resolution: "8MP 4K (3840×2160)", night_vision: "30m color activo", ip_rating: "IP67", connectivity: "PoE", fov: "95°", audio: "Sirena + altavoz", storage: "MicroSD hasta 256GB" },
    is_active: true,
    created_at: "",
    updated_at: "",
    brand: mockBrands[3],
    category: mockCategories[3],
  },
];
